db_tier: db-f1-micro
db_highAvailability: false
db_pointInTimeRecovery: false
db_type: POSTGRES_14
azureTenant: trygdeetaten.no
kafkaPool: nav-dev
environment: dev
replicas_min: 2
replicas_max: 2
cpu: 50m
memory: 500Mi
external-host:
  - pdl-api.dev-fss-pub.nais.io
env:
  SPRING_PROFILES_ACTIVE: default,testdatareset
  PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: dev-fss.pdl.pdl-api
  SYKMELDINGER_FRONTEND_CLIENT_ID: dev-gcp:teamsykmelding:sykmeldinger
