db_tier: db-f1-micro
azureTenant: trygdeetaten.no
kafkaPool: nav-dev
environment: dev
replicas_min: 2
replicas_max: 2
cpu: 200m
memory: 400Mi
external-host:
  - pdl-api.dev-fss-pub.nais.io
env:
  SPRING_PROFILES_ACTIVE: default,testdatareset,tombstoneprodusering
  PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: dev-fss.pdl.pdl-api
  SYKMELDINGER_FRONTEND_CLIENT_ID: dev-gcp:teamsykmelding:sykmeldinger
