apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-syketilfelle
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/liveness
  readiness:
    path: /internal/health/readiness
  startup:
    path: /internal/health/liveness
    initialDelay: 40
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  kafka:
    pool: {{kafkaPool}}
  tokenx:
    enabled: true
  gcp:
    sqlInstances:
      - type: {{db_type}}
        tier: {{db_tier}}
        highAvailability: {{db_highAvailability}}
        pointInTimeRecovery: {{db_pointInTimeRecovery}}
        diskAutoresize: true
        databases:
          - name: flex-syketilfelle-db
        maintenance:
          day: 2
          hour: 2
  env:
  {{#each env}}
     - name: {{@key}}
       value: {{this}}
  {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: sykepengesoknad-backend
          namespace: flex
        - application: sykmeldinger
          namespace: teamsykmelding
        - application: sparenaproxy
          namespace: teamsykmelding
        - application: syfosmregler
          namespace: teamsykmelding
        - application: syfosmpapirregler
          namespace: teamsykmelding
        - application: dinesykmeldte-kafka
          namespace: teamsykmelding
        - application: syfosminfotrygd
          namespace: teamsykmelding          
    outbound:
      external:
  {{#each external-host}}
        - host: {{this}}
  {{/each}}
