apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-syketilfelle
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/liveness
  readiness:
    path: /internal/health/readiness
  startup:
    path: /internal/health/liveness
    initialDelay: 40
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 800Mi
    requests:
      cpu: 200m
      memory: 550Mi
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  kafka:
    pool: {{kafkaPool}}
  tokenx:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: {{db_tier}}
        diskAutoresize: true
        databases:
          - name: flex-syketilfelle-db
        maintenance:
          day: 2
          hour: 2
  env:
  {{#each env}}
     - name: {{@key}}
       value: {{this}}
  {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: sykepengesoknad-backend
          namespace: flex
          cluster: {{environment}}-gcp
        - application: sykmeldinger
          namespace: teamsykmelding
          cluster: {{environment}}-gcp
        - application: sparenaproxy
          namespace: teamsykmelding
          cluster: {{environment}}-gcp
        - application: syfosmregler
          namespace: teamsykmelding
          cluster: {{environment}}-gcp
        - application: syfosmpapirregler
          namespace: teamsykmelding
          cluster: {{environment}}-gcp
        - application: dinesykmeldte-kafka
          namespace: teamsykmelding
    outbound:
      external:
  {{#each external-host}}
        - host: {{this}}
  {{/each}}
