db_tier: db-custom-1-3840
db_highAvailability: true
db_pointInTimeRecovery: true
db_type: POSTGRES_14
azureTenant: nav.no
kafkaPool: nav-prod
environment: prod
replicas_min: 3
replicas_max: 4
cpu: 200m
memory: 1000Mi
external-host:
  - pdl-api.prod-fss-pub.nais.io
env:
  PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: prod-fss.pdl.pdl-api
  SYKMELDINGER_FRONTEND_CLIENT_ID: prod-gcp:teamsykmelding:sykmeldinger
  FLEX_SYKMELDINGER_FRONTEND_CLIENT_ID: dev-gcp:flex:ditt-sykefravaer
