db_tier: db-custom-1-3840
db_type: POSTGRES_12
azureTenant: nav.no
kafkaPool: nav-prod
environment: prod
replicas_min: 0
replicas_max: 0
cpu: 400m
memory: 800Mi
external-host:
  - pdl-api.prod-fss-pub.nais.io
env:
  PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: prod-fss.pdl.pdl-api
  SYKMELDINGER_FRONTEND_CLIENT_ID: prod-gcp:teamsykmelding:sykmeldinger
