apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-syketilfelle
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 3
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 200m
      memory: 100Mi
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  kafka:
    pool: {{kafkaPool}}
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        diskAutoresize: true
        databases:
          - name: flex-syketilfelle-db
